name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.4.1
        with:
          required-ros-distributions: rolling
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.6
        with:
          package-name: gazebo_gridmap_plugin
          import-token: ${{secrets.GITHUB_TOKEN}}
          target-ros2-distro: rolling
          colcon-defaults: |
            {
              "test": {
                "ctest-args": [
                "-LE", "copyright"
                ]
              }
            }
          vcs-repo-file-url: https://raw.githubusercontent.com/ivrolan/gazebo_gridmap_plugin/main/dependency_repos.repos

